### ISSUE TITLE
adapter does not support Bluetooth Low Energy

### ISSUE THREAD

**Issue by cn0xroot** [securing/gattacker#16]
nice project.
But,when i use CSR(Cambridge Silicon Radio CSR8510 ) adapter,noble warning: adapter does not support Bluetooth Low Energy (BLE, Bluetooth Smart).

```
DEBUG=ws-slave sudo node ws-slave
GATTacker ws-slave
noble warning: adapter does not support Bluetooth Low Energy (BLE, Bluetooth Smart).
               Try to run with environment variable:
               [sudo] NOBLE_HCI_DEVICE_ID=x node ...
ws -> connection
ws -> send: {"type":"stateChange","state":"unsupported"}
ws -> message: {"action":"stopScanning"}
```
```

node scan
Ws-slave address: 127.0.0.1
on open
unsupported
```
Which type adapter should i used?  CC2540?
thanks!

**Comment by jslawek** [comment]
Hi, 
CSR8510 definitely supports BLE. Do you have 2 different adapters maybe?
Check your adapters by `hciconfig` - without parameters will list all adapters.
Next, check support for v4.0 of specific adapter (you should see `HCI version: 4.0`:
```
# hciconfig hci0 version
hci0: Type: BR/EDR Bus: USB
BD Address: 54:4A:16:5D:6F:41 ACL MTU: 310:10 SCO MTU: 64:8
HCI Version: 4.0 (0x6) Revision: 0x22bb
LMP Version: 4.0 (0x6) Subversion: 0x22bb
Manufacturer: Cambridge Silicon Radio (10)
```
Noble/Bleno libs used by GATTacker by default take first adapter available. If your first adapter does not support BLE, just power it down (`hciconfig hci0 down`). Or simply edit `HCI_DEVICE_ID` in `config.env`.

**Comment by cn0xroot** [comment]
OK，get it.
i'll try to use other adapters,thank you so much.

**Comment by cn0xroot** [comment]
Cambridge Silicon Radio CSR8510 A10 
```
HCI Version: 4.0 (0x6) Revision: 0x22bb
LMP Version: 4.0 (0x6) Subversion: 0x22bb
Manufacturer: Cambridge Silicon Radio (10)
```
