### ISSUE TITLE
Error with node scan

### ISSUE THREAD

**Issue by igorfelluga** [securing/gattacker#30]
Hi
I have installed gattacker on a Raspberry Pi 3 b+, nodejs 8.17 but when a use scan command I get this:
`pi@magicmirror:~/node_modules/gattacker $ node scan -o
Ws-slave address: 192.168.1.117
Overwrite services file if exists.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 192.168.1.117:2846
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)`

I tried same in another raspi and got same error

**Comment by marquesn** [comment]
I'm also having the same problem!

**Comment by igorfelluga** [comment]
@marquesn you must run "sudo node ws-slave" and in other terminal or device "node scan"

It's working to me
