### ISSUE TITLE
Relay working only one way

### ISSUE THREAD

**Issue by rob-cowsley** [securing/gattacker#5]
A quick one to start off with - I've got the relay working in one direction (between a phone and another device) but the connection back from the device to the phone doesn't seem to go through the relay.

If the device is close enough it makes a direct connection back to the phone. If it's too far away it just hangs and times out.

I guess my first question is if this is expected behavior or if I should investigate further...?

**Comment by securing** [comment]
Hi,

can you provide a little bit more information on the device, and especially the problematic requests it sends back to the phone? Is it a notification response, or a read/write request?
Your device may implement Bluetooth 4.1 "multi mode" features - it may act in both the "central" and "peripheral" roles. After initial communication from the phone which acts as "central", the device may switch the role, and treat phone as "peripheral" while connecting back to it. In such case it may issue "write" or "read" request to the phone.

If that is the case - intercepting such communication is technically possible using noble+bleno, however not yet implemented in GATTacker.  For further diagnosis it will be helpful to compare btsnoop-hci.log from the phone of working and non-working connection.
On Android phone you can grab it in Settings->Developer options->Enable Bluetooth HCI snoop log. It saves the log in /sdcard/btsnoop_hci.log. Turn it on and off for new file. It is just a pcap format, you can inspect it in Wireshark, or use https://github.com/nccgroup/BLE-Replay. 

If that is not the case - other causes of the problem include among others packet MTU size, problems with multiple BT4 adapters on the same box, others...
Did you test it in the newest version? Did you spoof MAC address of the device? Did you run both noble and bleno on the same or separate boxes?

**Comment by rob-cowsley** [comment]
A re-install and re-scan of the devices resolved this. - Not sure what wasn't working the first time...
