### ISSUE TITLE
Unsupported manufacturer

### ISSUE THREAD

**Issue by adrain09** [securing/gattacker#6]
when i use mac_adv ,it return:

> Unsupported manufacturer
> Re-plug the interface and hit enter

what's wrong?
thank you for your help!

my manufacturer is:
> Manufacturer:   Intel Corp. (2)

that is mean this manufacturer is unsupport？

**Comment by adrain09** [comment]
I konw what's wrong!

**Comment by gciandro13** [comment]
@adrain09 Can you tell me how did you solve the problem?

**Comment by adrain09** [comment]
@gciandro13 sorry,  I forgot it，I'm giving up it now. I switched to btlejuice。
