### ISSUE TITLE
how relay the ble

### ISSUE THREAD

**Issue by adrain09** [securing/gattacker#7]
how replay the ble packet?

ps: sorry,my english is so poor！hh~

**Comment by jslawek** [comment]
Hi,

if you mean to "relay" - just run the GATTacker according to manual, and it will relay the packets, that's how it works...

If you mean to "replay" - GATTacker currently does not support that feature.
You have several options to replay intercepted packets:
- BlueZ - command-line gatttool, DBUS...
- mobile application, e.g. nRF Connect
https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp
- BTLEJuice 
https://github.com/DigitalSecurity/btlejuice
- BLE-replay (if you have hcidump)
https://github.com/nccgroup/BLE-Replay
- own scripts: node.js, python, GO...

**Comment by adrain09** [comment]
oh, thank you!  I mean it.

**Comment by securing** [comment]
Starting from GATTacker v0.2.0 there is experimental replay feature, more information:
https://github.com/securing/gattacker/wiki/Dump-and-replay
